// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	context2 "context"
	"github.com/google/wire"
	"go.uber.org/zap"
	"osm-search/pkg/di/config"
	"osm-search/pkg/di/context"
	"osm-search/pkg/di/kv"
	"osm-search/pkg/di/logger"
	"osm-search/pkg/di/searcher"
	"osm-search/pkg/http"
	"osm-search/pkg/http/http-router/controllers"
	"osm-search/pkg/http/usecases"
)

// Injectors from wire.go:

func InitializeSearcherService() (*http.Server, func(), error) {
	contextContext, cleanup, err := context.New()
	if err != nil {
		return nil, nil, err
	}
	logger, cleanup2, err := logger_di.New()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	kvdb, err := kv_di.New(contextContext)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	searcher, err := searcher_di.New(contextContext, kvdb)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	searchService := NewSearcherService(logger, searcher)
	server, err := NewSearchAPIServer(contextContext, logger, searchService)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return server, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var defaultSet = wire.NewSet(context.New, config.New, logger_di.New, kv_di.New, searcher_di.New)

var searcherSet = wire.NewSet(
	defaultSet,
	NewSearcherService,
	NewSearchAPIServer,
)

func NewSearcherService(log *zap.Logger, searcher usecases.Searcher) controllers.SearchService {
	return usecases.New(log, searcher)
}

func NewSearchAPIServer(ctx context2.Context, log *zap.Logger,
	searchService controllers.SearchService) (*http.Server, error) {
	api := http.NewServer(log)

	apiService, err := api.Use(
		ctx, log, searchService,
	)
	if err != nil {
		return nil, err
	}

	return apiService, nil
}
